name: mydotnetproject
 
on:
  push:
    branches:
      - develop
 
jobs:
  dotnet-publish:
    runs-on: 'self-hosted'
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
 
      - name: Publish project
        run: dotnet publish -c release src/Presentation/Nop.Web/Nop.Web.csproj -o develop
 
 
 